language: go

sudo: required
dist: trusty

go:
    - 1.8.x
    - 1.9.x

install:
  - sudo apt-get update
  - sudo apt-get install -y llvm-3.8 clang-3.8
  - go get -t -v ./...


script:
  - ./.travis/test.sh
  